/* Autogenerated by /usr/bin/halcompile on Sat Mar  7 08:49:09 2026 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:aprs_laserreg:");
MODULE_INFO(linuxcnc, "pin:inpower:float:0:in:Desired laser power at constant speed:None:None");
MODULE_INFO(linuxcnc, "pin:reqspd:float:0:in:Requested speed, connect to motion.requested-vel:None:None");
MODULE_INFO(linuxcnc, "pin:curspd:float:0:in:Current speed, connect to motion.current-vel:None:None");
MODULE_INFO(linuxcnc, "pin:velx:float:0:in:Current speed x component, connect to joint.0.vel-cmd:None:None");
MODULE_INFO(linuxcnc, "pin:vely:float:0:in:Current speed y component, connect to joint.1.vel-cmd:None:None");
MODULE_INFO(linuxcnc, "pin:share:float:0:in:Fraction of power given to pure Y movement, eg. 0.6:None:None");
MODULE_INFO(linuxcnc, "pin:outpower:float:0:out:Scaled output laser power:None:None");
MODULE_INFO(linuxcnc, "funct:_:1:Update the laser power");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_float_t *inpower;
    hal_float_t *reqspd;
    hal_float_t *curspd;
    hal_float_t *velx;
    hal_float_t *vely;
    hal_float_t *share;
    hal_float_t *outpower;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->inpower), comp_id,
        "%s.inpower", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->reqspd), comp_id,
        "%s.reqspd", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->curspd), comp_id,
        "%s.curspd", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->velx), comp_id,
        "%s.velx", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->vely), comp_id,
        "%s.vely", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->share), comp_id,
        "%s.share", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->outpower), comp_id,
        "%s.outpower", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of aprs_laserreg");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of aprs_laserreg");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("aprs_laserreg");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "aprs-laserreg.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int j,idx;
        char *ptr;
        char buf[HAL_NAME_LEN+1];
        ptr = names;
        idx = 0;
        for (i=0,j=0; i <= strlen(names); i++) {
            buf[j] = *(ptr+i);
            if ( (*(ptr+i) == ',') || (*(ptr+i) == 0) ) {
                buf[j] = 0;
                r = export(buf, idx);
                if (*(ptr+i+1) == 0) {break;}
                idx++;
                if(r != 0) {break;}
                j=0;
            } else {
                j++;
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef inpower
#define inpower (0+*__comp_inst->inpower)
#undef reqspd
#define reqspd (0+*__comp_inst->reqspd)
#undef curspd
#define curspd (0+*__comp_inst->curspd)
#undef velx
#define velx (0+*__comp_inst->velx)
#undef vely
#define vely (0+*__comp_inst->vely)
#undef share
#define share (0+*__comp_inst->share)
#undef outpower
#define outpower (*__comp_inst->outpower)


#line 16 "aprs_laserreg.comp"

#include <math.h>

FUNCTION(_) {

    outpower = inpower * (curspd / reqspd);
    
    float angle = atan2(fabs(velx), fabs(vely));  // angle away from y in radians
    float horz = angle / (0.5*M_PI);          // 1 when moving perfectly along x axis
    outpower *= share + (1-share) * horz;

    if ( outpower > inpower )
        outpower = inpower;        
    if ( outpower > 100 )
        outpower = 100;        
    if ( outpower < 0 )
        outpower = 0;

}

static int __comp_get_data_size(void) { return 0; }
