#!/bin/bash
halcmd setp optimat_o_spindle_chiller false
DATE=`date +"%Y-%m-%d %H:%M:%S"`
mosquitto_pub -h localhost -t /cnc/optimat/debug -m "# $DATE: SPINDLE CHILLER OFF (M103) ARGV[1]:$1 ARGV[2]:$2"
exit 0
